$id: Meta
additionalProperties: false
description: Metadata about a resource. The metadata about a resource. This is content
  in the resource that is maintained by the infrastructure. Changes to the content
  might not always be associated with version changes to the resource. [See https://hl7.org/fhir/R5/Meta.html]
links: []
properties:
  _lastUpdated:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``lastUpdated``.
  _profile:
    items:
      $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``profile``.
    type: array
  _source:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``source``.
  _versionId:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``versionId``.
  extension:
    description: May be used to represent additional information that is not part
      of the basic definition of the element. To make the use of extensions safe and
      managable, there is a strict set of governance applied to the definition and
      use of extensions. Though any implementer can define an extension, there is
      a set of requirements that SHALL be met as part of the definition of the extension.
    element_property: true
    items:
      $ref: Extension.yaml
    title: Additional content defined by implementations
    type: array
  fhir_comments:
    anyOf:
    - type: string
    - items:
        type: string
      type: array
    element_property: false
    title: Fhir Comments
  id:
    description: Unique id for the element within a resource (for internal references).
      This may be any string value that does not contain spaces.
    element_property: true
    pattern: '[ \r\n\t\S]+'
    title: Unique id for inter-element referencing
    type: string
  lastUpdated:
    description: When the resource last changed - e.g. when the version changed.
    element_property: true
    format: date-time
    title: When the resource version last changed
    type: string
  links:
    items:
      $ref: https://json-schema.org/draft/2020-12/links
    type: array
  profile:
    description: A list of profiles (references to [StructureDefinition](structuredefinition.html#)
      resources) that this resource claims to conform to. The URL is a reference to
      [StructureDefinition.url](structuredefinition-definitions.html#StructureDefinition.url).
    element_property: true
    enum_reference_types:
    - StructureDefinition
    items:
      pattern: \S*
      type: string
    title: Profiles this resource claims to conform to
    type: array
  resourceType:
    const: Meta
    default: Meta
    description: One of the resource types defined as part of FHIR
    title: Resource Type
    type: string
  security:
    binding_description: Security Labels from the Healthcare Privacy and Security
      Classification System.
    binding_strength: extensible
    binding_uri: http://hl7.org/fhir/ValueSet/security-labels
    binding_version: null
    description: Security labels applied to this resource. These tags connect specific
      resources to the overall security policy and infrastructure.
    element_property: true
    items:
      $ref: Coding.yaml
    title: Security Labels applied to this resource
    type: array
  source:
    description: A uri that identifies the source system of the resource. This provides
      a minimal amount of [Provenance](provenance.html#) information that can be used
      to track or differentiate the source of information in the resource. The source
      may identify another FHIR server, document, message, database, etc.
    element_property: true
    pattern: \S*
    title: Identifies where the resource comes from
    type: string
  tag:
    binding_description: Codes that represent various types of tags, commonly workflow-related;
      e.g. "Needs review by Dr. Jones".
    binding_strength: example
    binding_uri: http://hl7.org/fhir/ValueSet/common-tags
    binding_version: null
    description: Tags applied to this resource. Tags are intended to be used to identify
      and relate resources to process and workflow, and applications are not required
      to consider the tags when interpreting the meaning of a resource.
    element_property: true
    items:
      $ref: Coding.yaml
    title: Tags applied to this resource
    type: array
  versionId:
    description: The version specific identifier, as it appears in the version portion
      of the URL. This value changes when the resource is created, updated, or deleted.
    element_property: true
    maxLength: 64
    minLength: 1
    pattern: ^[A-Za-z0-9\-.]+$
    title: Version specific identifier
    type: string
title: Meta
type: object
